import type { A11yProperties } from "./types.ts";
export declare function computeLevel(el: Element, role: string): number | undefined;
export declare function computeHaspopup(el: Element): string | boolean | undefined;
export declare function computeOrientation(el: Element): "horizontal" | "vertical" | undefined;
export declare function computeMultiselectable(el: Element): boolean | undefined;
export declare function computeAutocomplete(el: Element): string | undefined;
export declare function computeValuemin(el: Element): number | undefined;
export declare function computeValuemax(el: Element): number | undefined;
export declare function computeValuenow(el: Element): number | undefined;
export declare function computeValuetext(el: Element): string | undefined;
export declare function computePosinset(el: Element): number | undefined;
export declare function computeSetsize(el: Element): number | undefined;
export declare function computeColcount(el: Element): number | undefined;
export declare function computeColindex(el: Element): number | undefined;
export declare function computeColspan(el: Element): number | undefined;
export declare function computeRowcount(el: Element): number | undefined;
export declare function computeRowindex(el: Element): number | undefined;
export declare function computeRowspan(el: Element): number | undefined;
export declare function computeSort(el: Element): "ascending" | "descending" | "none" | "other" | undefined;
export declare function computeProperties(el: Element, role: string): A11yProperties | undefined;
